stages:
  - clone
  - setup
  - initialize
  - plan
  - apply
  - test
  - cleanup

variables:
  TF_VERSION: "1.10.5"
  TF_PROJECT_DIR: "/builds/naidhilebhuvana/Terraform_Project"

image: alpine:latest

services:
  - name: docker:20.10.7-dind
    alias: docker
    command: ["--host=tcp://0.0.0.0:2375"]

before_script:
  - echo "Installing required tools..."
  - apk add --no-cache curl unzip git docker
  - echo "Installing Terraform..."
  - curl -LO https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
  - unzip -o terraform_${TF_VERSION}_linux_amd64.zip
  - mv terraform /usr/local/bin/
  - terraform --version
  - export DOCKER_HOST=tcp://docker:2375  # Make sure it's using the correct Docker service address
  - echo "Waiting for Docker daemon to initialize..."
  - sleep 30  # Allow Docker time to initialize fully
  - docker ps || (echo "Docker is not running correctly" && exit 1)

clone:
  stage: clone
  script:
    - |
      echo "Cleaning up existing directory..."
      rm -rf /builds/naidhilebhuvana/Terraform_Project
      mkdir -p /builds/naidhilebhuvana/Terraform_Project
      chmod -R 777 /builds/naidhilebhuvana/Terraform_Project
      echo "Current directory: $(pwd)"
      echo "Cloning the repository..."
      cd /builds/naidhilebhuvana/Terraform_Project
      git clone https://github.com/Naidhile/Terraform_Project.git .
      echo "Repository cloned."

setup:
  stage: setup
  script:
    - |
      echo "Setting up Terraform directory..."
      cd $TF_PROJECT_DIR
      echo "Setup complete."

initialize:
  stage: initialize
  script:
    - |
      echo "Initializing Terraform..."
      terraform init
      echo "Terraform initialization complete."

plan:
  stage: plan
  script:
    - |
      terraform init
      echo "Running Terraform plan..."
      terraform plan -out=plan.tfout -var="container_name=my_container" -var="image=nginx:latest" -var="external_port=8082" -input=false
      ls -l plan.tfout

apply:
  stage: apply
  script:
    - |
      echo "Applying Terraform plan..."
      ls -l plan.tfout
      terraform apply -auto-approve plan.tfout
      echo "Terraform apply complete."

test:
  stage: test
  script:
    - |
      echo "Running tests..."
      terraform show
      echo "Tests complete."

cleanup:
  stage: cleanup
  script:
    - |
      echo "Cleaning up Terraform state..."
      terraform destroy -auto-approve
      echo "Cleanup complete."
