stages:
  - clone
  - setup
  - initialize
  - plan
  - apply
  - test
  - cleanup

variables:
  GITHUB_REPO: "Naidhile/Terraform_Project"
  DOCKER_USER: "Naidhile"

clone_repository:
  stage: clone
  script:
    - echo "Cloning GitHub repository for Terraform configuration files..."
    - git clone https://github.com/$GITHUB_REPO.git

install_dependencies:
  stage: setup
  script:
    - echo "Setting up environment for Terraform..."
    - echo docker run -d --name terraform-env hashicorp/terraform:latest

initialize_terraform:
  stage: initialize
  script:
    - echo "Initializing Terraform..."
    - echo docker exec -i terraform-env terraform init

plan_infrastructure:
  stage: plan
  script:
    - echo "Creating Terraform execution plan..."
    - echo docker exec -i terraform-env terraform plan -out=tfplan

apply_configuration:
  stage: apply
  script:
    - echo "Applying Terraform configuration..."
    - echo docker exec -i terraform-env terraform apply -auto-approve tfplan

test_configuration:
  stage: test
  script:
    - echo "Testing deployed infrastructure..."
    - echo docker exec -i terraform-env terraform output

cleanup:
  stage: cleanup
  script:
    - echo "Cleaning up the environment..."
    -  echo docker rm -f terraform-env