stages:
  - clone
  - setup
  - init
  - validate
  - plan
  - apply
  - test

variables:
  TF_ENV: "dev"  # Specify the environment (dev, staging, production)
  TF_WORKING_DIR: "environment/$TF_ENV"
  TF_VERSION: "1.5.0"

image: nginx:latest  # Use nginx latest image

services:
  - docker:dind  # Docker-in-Docker service to enable Docker commands

before_script:
  - apt-get update && apt-get install -y unzip curl
  - echo "Installing Docker..."
  - curl -fsSL https://get.docker.com | bash  # Install Docker
  - docker --version  # Verify Docker installation
  - terraform --version || echo "Terraform is managed by Docker"

clone_repository:
  stage: clone
  script:
    - echo "Cloning GitHub repository for Terraform configuration files..."
    - git clone https://github.com/Naidhile/Terraform_Project.git


install_dependencies:
  stage: setup
  script:
    - echo "Setting up environment for Terraform..."
    - docker pull kreuzwerker/docker:2.0.0   # Pull the image for running Terraform
    - docker ps -a -q --filter "name=terraform-env" | xargs --no-run-if-empty docker rm -f  # Clean up old containers
    - docker run -d --name terraform-env kreuzwerker/docker:2.0.0
    - docker ps  # Verify the container is running


# Stage 1: Initialize Terraform
terraform-init:
  stage: init
  script:
    - echo "Initializing Terraform for $TF_ENV environment..."
    - cd $TF_WORKING_DIR
    - docker run --rm -v $(pwd):/workspace -w /workspace kreuzwerker/docker:2.0.0 init

# Stage 2: Validate Terraform
terraform-validate:
  stage: validate
  script:
    - echo "Validating Terraform configuration..."
    - cd $TF_WORKING_DIR
    - docker run --rm -v $(pwd):/workspace -w /workspace kreuzwerker/docker:2.0.0 validate


# Stage 3: Plan Terraform Changes
terraform-plan:
  stage: plan
  script:
    - echo "Planning Terraform changes..."
    - cd $TF_WORKING_DIR
    - docker run --rm -v $(pwd):/workspace -w /workspace kreuzwerker/docker:2.0.0 plan -out=tfplan
  artifacts:
    paths:
      - $TF_WORKING_DIR/tfplan

# Stage 4: Apply Terraform Changes
terraform-apply:
  stage: apply
  script:
    - echo "Applying Terraform changes..."
    - cd $TF_WORKING_DIR
    - docker run --rm -v $(pwd):/workspace -w /workspace kreuzwerker/docker:2.0.0 apply -auto-approve tfplan

test_configuration:
  stage: test
  script:
    - echo "Testing deployed infrastructure..."
    - docker exec -i terraform-env terraform output

