stages:
  - clone
  - setup
  - init
  - validate
  - plan
  - apply
  - test

variables:
  TF_ENV: "dev"  # Specify the environment (dev, staging, production)
  TF_WORKING_DIR: "environment/$TF_ENV"  # Working directory path
  TF_VERSION: "1.5.0"  # Define the version of Terraform to use

image: nginx:latest  # Use nginx latest image

services:
  - docker:dind  # Docker-in-Docker service to enable Docker commands

before_script:
  - apt-get update && apt-get install -y unzip curl
  - echo "Installing Docker..."
  - curl -fsSL https://get.docker.com | bash  # Install Docker
  - docker --version  # Verify Docker installation
  - terraform --version || echo "Terraform will be managed by Docker"  # Check if Terraform is installed, else it'll be handled by Docker


clone_repository:
  stage: clone
  script:
    - echo "Cloning GitHub repository for Terraform configuration files..."
    - git clone https://github.com/Naidhile/Terraform_Project.git
    - ls -al 

install_dependencies:
  stage: setup
  script:
    - echo "Setting up environment for Terraform..."
    - docker run -d --name terraform-env kreuzwerker/terraform:latest # Run a new container for Terraform

terraform-init:
  stage: init
  script:
    - echo "Initializing Terraform for $TF_ENV environment..."
    - cd $TF_WORKING_DIR
    - docker run --rm -v $(pwd):/workspace -w /workspace kreuzwerker/terraform:latest init  # Initialize Terraform in the container

terraform-validate:
  stage: validate
  script:
    - echo "Validating Terraform configuration..."
    - cd $TF_WORKING_DIR
    - docker run --rm -v $(pwd):/workspace -w /workspace kreuzwerker/terraform:latest validate  # Validate the Terraform configuration

terraform-plan:
  stage: plan
  script:
    - echo "Planning Terraform changes..."
    - cd $TF_WORKING_DIR
    - docker run --rm -v $(pwd):/workspace -w /workspace kreuzwerker/terraform:latest plan -out=tfplan  # Plan the changes
  artifacts:
    paths:
      - $TF_WORKING_DIR/tfplan  # Save the plan file as an artifact

terraform-apply:
  stage: apply
  script:
    - echo "Applying Terraform changes..."
    - cd $TF_WORKING_DIR
    - docker run --rm -v $(pwd):/workspace -w /workspace kreuzwerker/terraform:latest apply -auto-approve tfplan  # Apply the plan automatically

test_configuration:
  stage: test
  script:
    - echo "Testing deployed infrastructure..."
    - docker exec -i terraform-env terraform output  # Test and fetch Terraform output from the container
