name: Trigger GitLab Pipeline

on:
  push:
    branches:
      - master  # Trigger when code is pushed to the main branch

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger GitLab Pipeline
        run: |
          curl --request POST --form token=glptt-9ad9853756c8ee8a269d888357d680c6ec790d31 --form ref=main https://gitlab.com/api/v4/projects/66061264/trigger/pipeline
        env:
          GITLAB_TRIGGER_TOKEN: ${{ secrets.GITLAB_TRIGGER_TOKEN }}
