name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.0.0"

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=plan.tfout

      - name: Terraform Apply
        run: terraform apply -auto-approve plan.tfout

      - name: Terraform Destroy
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: terraform destroy -auto-approve
